version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/spring-boot-mongo/
hooks:
  AfterInstall:
   - location: setup.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: run.sh
     timeout: 300
     runas: root
  ApplicationStop:
   - location: ron.sh
     timeout: 300
     runas: root
  BeforeInstall:
   - location: cies.sh
     timeout: 300
     runas: root
